import test1 as test1
import test2 as test2

if __name__ == '__main__':
    test1.test_compute_z()
    test1.test_compute_a()
    test1.test_compute_L()
    test1.test_forward()
    test1.test_check_dL_da()
    test1.test_check_dL_da()
    test1.test_check_da_dz()
    test1.test_check_da_dz()
    test1.test_check_dz_dW()
    test1.test_check_dz_db()
    test1.test_backward()
    test1.test_compute_dL_dz()
    test1.test_compute_dL_dW()
    test1.test_check_dL_dW()
    test1.test_check_dL_db()
    test1.test_update_W()
    test1.test_update_b()
    test1.test_train()
    test1.test_predict()
    test1.test_softmax_regression()

    test2.test_compute_z1()
    test2.test_compute_a1()
    test2.test_compute_z2()
    test2.test_compute_a2()
    test2.test_forward()
    test2.test_compute_dL_da2()
    test2.test_compute_da2_dz2()
    test2.test_compute_dz2_dW2()
    test2.test_compute_dz2_db2()
    test2.test_compute_dz2_da1()
    test2.test_compute_da1_dz1()
    test2.test_compute_dz1_dW1()
    test2.test_compute_dz1_db1()
    test2.test_backward()
    test2.test_compute_dL_da1()
    test2.test_compute_dL_dz1()
    test2.test_compute_gradients()
    test2.test_check_compute_gradients()
    test2.test_fully_connected()
